# Generated by Django 3.1.6 on 2021-05-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='doctorID',
            field=models.ForeignKey(db_column='doctorID', default='', on_delete=django.db.models.deletion.CASCADE, related_name='treatmentPlan_doctorID', to='reservations.doctor'),
        ),
    ]
