# Generated by Django 3.1.6 on 2021-05-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_treatmentplan_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorPhone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sPhone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
