# Generated by Django 3.1.6 on 2021-05-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20210527_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='appointmentLimit',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
