export const GET_PATIENTS = "GET_PATIENTS";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const ADD_PATIENT = "ADD_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const GET_SPECIFIC_PATIENT = "GET_SPECIFIC_PATIENT";

export const GET_DOCTORS = "GET_DOCTORS";
export const DELETE_DOCTOR = "DELETE_DOCTOR";
export const ADD_DOCTOR = "ADD_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";

export const GET_STAFFS = "GET_STAFFS";
export const DELETE_STAFF = "DELETE_STAFF";
export const ADD_STAFF = "ADD_STAFF";
export const UPDATE_STAFF = "UPDATE_STAFF";

export const GET_WORKSCHEDULES = "GET_WORKSCHEDULES";
export const DELETE_WORKSCHEDULE = "DELETE_WORKSCHEDULE";
export const ADD_WORKSCHEDULE = "ADD_WORKSCHEDULE";

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const GET_SPECIFIC_APPOINTMENT = "UPDATE_APPOINTMENT";

export const GET_PRESCRIPTIONS = "GET_PRESCRIPTIONS";
export const DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION";
export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";
export const GET_SPECIFIC_PRESCRIPTION = "GET_SPECIFIC_PRESCRIPTION";

export const GET_TREATMENTPLANS = "GET_TREATMENTPLANS";
export const DELETE_TREATMENTPLAN = "DELETE_TREATMENTPLAN";
export const ADD_TREATMENTPLAN = "ADD_TREATMENTPLAN";
export const UPDATE_TREATMENTPLAN = "UPDATE_TREATMENTPLAN";
export const GET_SPECIFIC_TREATMENTPLAN = "GET_SPECIFIC_TREATMENTPLAN";

//============================================== TYPES FOR AUTH ======================================================================

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const UPDATE_AUTH_USER = "UPDATE_AUTH_USER";
export const REGISTER_BY_STAFF_FAIL = "REGISTER_BY_STAFF_FAIL";
export const REGISTER_BY_STAFF_SUCCESS = "REGISTER_BY_STAFF_SUCCESS";
export const DELETE_AUTH_USER = "DELETE_AUTH_USER";
